language: php

php:
    - 7.0
    - 7.1

before_script:
    - composer install --prefer-dist
    - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar

script:
    - mkdir -p build/logs
    - bin/check-code-cov
    - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover ./build/logs/clover.xml

after_script:
    - php coveralls.phar -v

branches:
  only:
    - develop
