# TravisCI configuration for mihaeu/dephpend

language: "php"
os:
    - "linux"
dist: "bionic"

php:
    - "8.0"
    - "8.1"

install:
    - "mkdir -p build/logs"
    - "composer validate --strict"
    - "composer install --prefer-dist"

script:
    - "bin/check-code-cov"
    - "vendor/bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover ./build/logs/clover.xml"

after_script:
    - "wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.2/php-coveralls.phar"
    - "php php-coveralls.phar -v"
